### ISSUE TITLE
problem with pip install

### ISSUE THREAD

**Issue by bolg4r** [Fafa87/cellstar#18]
Hi, i have an issue with installing your great package into venv with pip on Windows
I am going with 
pip install cellstar 
and get this error
Collecting matplotlib<=2.2.5 (from cellstar)
  Using cached matplotlib-2.2.5.tar.gz (36.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      ============================================================================
      Edit setup.cfg to change the build options

      BUILDING MATPLOTLIB
                  matplotlib: yes [2.2.5]
                      python: yes [3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021,
                              18:08:50) [MSC v.1929 64 bit (AMD64)]]
                    platform: yes [win32]

      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [not found. pip may install it below.]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype
                              (freetype2\ft2build.h) could not be found.  You may
                              need to install the development package.]
                         png: no  [The C/C++ header for png (png.h) could not be
                              found.  You may need to install the development
                              package.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]

      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]

      OPTIONAL BACKEND EXTENSIONS
                      macosx: no  [Mac OS-X only]
                      qt5agg: no  [PySide2 not found; PyQt5 not found]
                      qt4agg: no  [PySide not found; PyQt4 not found]
                     gtk3agg: no  [Requires pygobject to be installed.]
                   gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                      gtkagg: no  [Requires pygtk]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                       wxagg: no  [requires wxPython]
                         gtk: no  [Requires pygtk]
                         agg: yes [installing]
                       cairo: no  [cairocffi or pycairo not found]
                   windowing: yes [installing]

      OPTIONAL LATEX DEPENDENCIES
                      dvipng: no
                 ghostscript: no
                       latex: no
                     pdftops: no

      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]

      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
                              * Please check http://gnuwin32.sourceforge.net/packa
                              * ges/freetype.htm for instructions to install
                              * freetype
                              * Please check http://gnuwin32.sourceforge.net/packa
                              * ges/libpng.htm for instructions to install png
      [end of output]

i am using pycharm, python 3.9. I am really  new in python. Can you help me, please?
I also have tried to install matlab package, but have not found
Our team really appreciate your work, and we hope we can try it by ourselves
 
 Thanks for answering!

**Comment by Fafa87** [comment]
Hi!

I will try to reproduce that on my end. I see you are on Windows, right?
What are you using for venv? conda? mamba?

**Comment by Fafa87** [comment]
What I did on my Windows 10 machine:
- `mamba create -n cellstar_18 python=3.9` - this creates new env with python=3.9
- `mamba activate cellstar_18` - activate that env
- `pip install cellstar` 

... and I get the same error as you :)
I will figure it out and let you know.

**Comment by Fafa87** [comment]
Seems that there are no pre-build wheels for matplotlib==2.2.5 and python==3.9 combination:
- https://pypi.org/project/matplotlib/2.2.5/#files
Therefore it tries to build matplotlib from source and fails to do so.
It is weird because I could swear I was testing that but maybe it was building from sources on that machine.

As a workaround you can install matplotlib using mamba (it has it already built) and then pip install:
- `mamba install matplotlib==2.2.5`
- `pip install cellstar`
In installing cellstar it should skip matplotlib as below:
![image](https://github.com/Fafa87/cellstar/assets/9865688/285bd845-dda3-46db-a7fd-f0aebd02d6dd)

**But then it fails for pillow** for lack of python 3.9 version - now I understand why I only specified python 3.8 on the repo main page. I guess thats why it worked on my other machine.
![image](https://github.com/Fafa87/cellstar/assets/9865688/feafb8a1-67b0-48e8-94d8-de600ab35a83)

If you could downgrade to python=3.8 it should install cleanly. 
If not we could do the same trick by using mamba:
- `mamba install pillow==6.6.2`

But it is not found in mamba/anaconda channels:
`package pillow-6.2.2-py38h1d4d63c_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed`
I guess it was never build for python=3.9 - seems not supported as stated by their site:
- https://pillow.readthedocs.io/en/latest/installation.html

**Hmm seems that I will have to find a set of versions for python=3.9 and up.** 
I will try to do it this evening.

**As a sidenote:**
![image](https://github.com/Fafa87/cellstar/assets/9865688/db728f6c-7c96-49fb-a132-8ca284438a87)
Above you can see that pip is downloading already build package (cp39 means that it is for python3.9)
But for matplotlib it is grabbing the source code - which has to be build because e.g. it contains some c code as well:
![image](https://github.com/Fafa87/cellstar/assets/9865688/c208a419-0d96-4b63-94e2-fe22ec416456)

**Comment by Fafa87** [comment]
I have released cellstar version 2.0.3 which has updated packages and should be able to install cleanly in python 3.9.
Let me know if it resolves issue for you.

**Comment by bolg4r** [comment]
it all worked out, thanks!!!
